# Generated by Django 5.2 on 2025-04-20 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('employee_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('basic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport', models.DecimalField(decimal_places=2, max_digits=10)),
                ('education', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary.employee')),
            ],
        ),
    ]
